### ISSUE TITLE
在nexus 6P中删除 @XXX 无法整体删除

### ISSUE THREAD

**Issue by llkkzz111** [sunhapper/SpEditTool#1]
在nexus 6P中删除 @XXX 无法整体删除
Nexus 6P  8.1.0

**Comment by sunhapper** [comment]
我测试时google输入法英文状态下会有这个问题，中文状态下正常，和系统版本没有必然联系，同时@功能在微信上表现也是一样，麻烦确认下你的问题是不是也是这样

**Comment by llkkzz111** [comment]
是的 微信也有类似问题 同样是 google输入法

**Comment by sunhapper** [comment]
问题已修复 [delete content by InputConnectionWrapper](https://github.com/sunhapper/SpEditTool/commit/f89056feefd48ad3174b0e13c3b57320916dd458)

**Comment by sunhapper** [comment]
感谢你的反馈
现在做了如下处理
* 使用InputConnectionWrapper代替setOnKeyListener监听输入法删除键
* 每次删除都会判断SpData标记的字符串完整性，不完整会remove对应SpData和自定义样式，保证异常情况下数据不会出现问题

请将版本更新到0.2.2
