### ISSUE TITLE
关于SelectDeleteKeyEventProxy

### ISSUE THREAD

**Issue by Khaos116** [sunhapper/SpEditTool#12]
![H`VB`G`P2GJ{NAD_XO{F9Y1](https://user-images.githubusercontent.com/11989916/59004531-80204000-884c-11e9-99b1-98d43cb78142.png)

![I2S8L%WT71`C5HL0X)(ZTMS](https://user-images.githubusercontent.com/11989916/59004595-b78eec80-884c-11e9-9412-efa62e6e315a.png)
可以通过替换效果的方式设置删除选中状态spanStringBg，但是需要处理一下选中后不删除，光标移动，需要重新设置为spanStringFore的非选中状态效果(spanStringBg相比spanStringFore多设置一个BackgroundColorSpan属性)

**Comment by Khaos116** [comment]
MentionUser文件
![M)79{CO}WW1YR7$X HZAF5C](https://user-images.githubusercontent.com/11989916/59005108-ca0a2580-884e-11e9-93af-82ca21d03eba.png)

**Comment by Khaos116** [comment]
SpanChangedWatcher文件
![UQ((2J1 M5I0Y _`K7} N~2](https://user-images.githubusercontent.com/11989916/59005149-f625a680-884e-11e9-8875-ce48a77f8c24.png)
在Selection.SELECTION_START操作的方式可能有点不好，可以找找更好的方法

**Comment by sunhapper** [comment]
没太明白为什么底层的代码需要依赖MentionUser的功能
还有这个代码要实现的效果是什么样的

**Comment by Khaos116** [comment]
@sunhapper 为了你注释的那个删除没有先选中@的内容再执行删除啊。我只是提供一个思路，并不一定要这样实现，代码层次可以调整哇

**Comment by Khaos116** [comment]
效果图
![Peek 2019-06-06 14-49](https://user-images.githubusercontent.com/11989916/59012555-67268780-886a-11e9-86a2-4c629753ce99.gif)

**Comment by sunhapper** [comment]
感谢反馈，尝试了下确实可行
