### ISSUE TITLE
使用了不同textSize的TextView，表情的大小会和文字大小出现不一致的情况

### ISSUE THREAD

**Issue by CnyNer** [sunhapper/SpEditTool#13]
![image](https://user-images.githubusercontent.com/12473524/59419818-4926cd00-8dfe-11e9-8a53-af0e264f7d81.png)
我是通过这样把图片set进去的，但是在列表上，有时候会显示，有时候会消失；

**Comment by CnyNer** [comment]
@sunhapper 你好，请问有联系方式吗？当在list里面有多个item是sptext的时候，会有复用问题存在。想跟你讨论一下谢谢。

**Comment by sunhapper** [comment]
不好意思，最近比较忙，没太顾得过来这块
联系方式不方便放，直接这个issues讨论吧
方便的话能不能把你的场景写个demo放github上？我看看怎么解决

**Comment by CnyNer** [comment]
@sunhapper 好的，我现在就是用你的demo在RecyclerDemoActivity中改了 两个场景你自己看一下；

1、第一种。是把list里面的item的text字号改大到30sp。这样改的话，会使得第一个item的icon变的很小。我andorid9没问题。8.0和8.1好像就有问题。
![image](https://user-images.githubusercontent.com/12473524/59905996-274ecb00-943a-11e9-9628-8a2476ae5680.png)

前面的icon是通过SpannableStringBuilder

![image](https://user-images.githubusercontent.com/12473524/59906025-39306e00-943a-11e9-8e2f-cfc81b2ce7cd.png)
![image](https://user-images.githubusercontent.com/12473524/59906028-3cc3f500-943a-11e9-9399-87cd001b3d62.png)

这样放进去的。


2.di'er第二个场景也是这个页面，在一个item里面多复制一个text

**Comment by CnyNer** [comment]
![image](https://user-images.githubusercontent.com/12473524/59906080-58c79680-943a-11e9-84fa-d8304763f418.png)

这样zi字，前面也是头部也是分别放两个gilde加载的icon。这样图标就会错乱了、。你试试第一个先。看看怎么解决。

**Comment by CnyNer** [comment]
![image](https://user-images.githubusercontent.com/12473524/59906124-7f85cd00-943a-11e9-99d9-253bec95a405.png)


IsoheightImageSpan类中getSize的return bounds.right;这个值可能是为0.然后drawableHeight = fm.descent - fm.ascent;的值有时候在第一个item会变化，导致icon会大小变化。

可能考虑到GifWatcher中弱引用导致复用的问题还是怎样。求帮忙解决一下。用了你的框架。现在在富文本显示有bug。

**Comment by CnyNer** [comment]
![image](https://user-images.githubusercontent.com/12473524/59906361-2702ff80-943b-11e9-8c05-c84ed82d35b7.png)

**Comment by CnyNer** [comment]
我已经截图给你了，麻烦你看看。
发自我的iPhone

------------------ 原始邮件 ------------------
发件人: sunhapper <notifications@github.com>
发送时间: 2019年6月21日 15:19
收件人: sunhapper/SpEditTool <SpEditTool@noreply.github.com>
抄送: HuiMing Yuan <447348267@qq.com>, Author <author@noreply.github.com>
主题: 回复：[sunhapper/SpEditTool] 用glide加载GifDrawable在列表中，时而加载成功显示而消失；不知道是不是复用的问题； (#13)




不好意思，最近比较忙，没太顾得过来这块
 联系方式不方便放，直接这个issues讨论吧
 方便的话能不能把你的场景写个demo放github上？我看看怎么解决

**Comment by sunhapper** [comment]
感谢反馈，表情大小的问题已修复，还有其他问题，请另外提issue，谢谢
