### ISSUE TITLE
导入工程一直失败

### ISSUE THREAD

**Issue by paulpaulzhang** [sunhapper/SpEditTool#16]
换了一个demo也一样

ERROR: Failed to resolve: com.github.sunhapper:SpEditTool:SpEditText

**Comment by sunhapper** [comment]
感谢反馈
改成这样的依赖试下
implementation 'com.github.sunhapper.SpEditTool:SpEditText:1.0.3'
implementation 'com.github.sunhapper.SpEditTool:SpGlideDrawable:1.0.3'
implementation 'com.github.sunhapper.SpEditTool:SpGifDrawable:1.0.3'

**Comment by paulpaulzhang** [comment]
正常了，谢谢
