### ISSUE TITLE
不知道有没有考虑过 复制粘贴的功能

### ISSUE THREAD

**Issue by llkkzz111** [sunhapper/SpEditTool#2]
不知道有没有考虑过 复制粘贴的功能，尤其是自定义的表情 ，如果有对应的TextView最好

**Comment by sunhapper** [comment]
复制粘贴功能应当是外部处理的，不适合封装在控件里面，除非是为了做某个样式的复制粘贴效果,这不是我写这个库的本来目的

**Comment by llkkzz111** [comment]
复制然后粘贴的话 自定义的 表情 会变成原始编码

**Comment by sunhapper** [comment]
我试了下确实是这样，想了下原因，因为剪切板是系统的service，所以它不可能知道我们应用中实现的自定义的ImageSpan，SpData等等逻辑，所以复制到剪切板的时候这些信息会丢失

提供两种解决思路
* 自己维护一个应用内的剪切板，将复制的CharSequence保存起来并且也向系统的剪切板里塞数据（保证应用外的粘贴有效），粘贴的时候先去系统剪切板的数据，和应用内剪切板的数据比较，相同就用应用内的，不同就用系统的，同时更新应用内剪切板的数据。
* 第二种是写一个解析工具，在设置文本到TextView之前先解析转换下文本内容再设置，这个在demo中`EmojiManager.getSpannableByPattern()`中有具体的实现，你可以先看下

**Comment by sunhapper** [comment]
上面两种方案都需要自己自定义实现复制粘贴的逻辑，可以搜搜相关文章

**Comment by llkkzz111** [comment]
我的思路是在粘贴的时候对emoji 进行单独处理，但是这样子需要遍历整个粘贴的字符串。
