### ISSUE TITLE
当从服务器拿数据回来，用TextView展示以及设置点击事件时一般怎么处理呢？求大神指教

### ISSUE THREAD

**Issue by liangtian123** [sunhapper/SpEditTool#21]

**Comment by sunhapper** [comment]
一般根据服务器数据里面对应要点击的部分创建ClickableSpan，要结合我的库的话可以看下demo里面MentionUser里面的用法，把MentionUser继承ClickableSpan或者持有一个ClickableSpan应该都是可以实现点击
