### ISSUE TITLE
添加依赖无法通过编译

### ISSUE THREAD

**Issue by AwaiTYu** [sunhapper/SpEditTool#4]
你好，我添加依赖之后，编译无法通过，但是把你的libary下载下来加到项目中，让app添加这个libary是么问题的编译也正常通过，原因貌似是我项目中用的Glide是3.7的而你的是用的4.0的，我猜想添加你的依赖之后可能把你的demo的gradle也添加过来了，导致编译无法通过

**Comment by sunhapper** [comment]
能把编译的报错信息粘贴过来我看下吗，谢谢

**Comment by AwaiTYu** [comment]
![one](https://user-images.githubusercontent.com/28527497/40304791-9f641386-5d2a-11e8-9b4e-f2ee18ae53fa.png)
![two](https://user-images.githubusercontent.com/28527497/40304798-a2bd5d9e-5d2a-11e8-95b2-d5a8adc1f262.png)

**Comment by AwaiTYu** [comment]
希望我没有犯什么低级错误

**Comment by sunhapper** [comment]
'com.github.sunhapper:SpEditTool:{last version}'应该换成'com.github.sunhapper:SpEditTool:0.2.3'，你试下，libary中应该没依赖glide，demo里面才依赖的
