### ISSUE TITLE
如果需要动态匹配表情该如何实现

### ISSUE THREAD

**Issue by magic0908** [sunhapper/SpEditTool#5]
首先感谢作者的开源库，不过我遇到了一个问题
比如我想实现类似朋友圈列表那样的文字和gif表情展示，后台可能返回这样一串文本
“今天天气很好[emt]3[/emt]”，客户端需要使用正则表达式去动态匹配并显示gif，但是我看了demo并尝试按照上面的规则显示gif，却没有显示出来

**Comment by sunhapper** [comment]
抱歉隔了这么久才回应，用正则表达式匹配表情应该是在设置TextView文本之前就处理好，具体可以参照`EmojiManager.getSpannableByPattern()`,不过正则规则每个人都不一样，需要自己实现
我在demo中加了一个简单的示例，可以看下
