### ISSUE TITLE
mention文字在前後移動游標後，輸入的文字會套用到mention的span style

### ISSUE THREAD

**Issue by ench0812** [sunhapper/SpEditTool#7]
![image](https://user-images.githubusercontent.com/8065895/52702263-c9efcc80-2fb6-11e9-8db2-fb447153a471.png)

**Comment by sunhapper** [comment]
你好，能详细描述下“前後移動游標”这个操作吗？我试了下没有出现你图中的情况
方便的话能提供下系统版本，输入法以及操作路径，谢谢

**Comment by ench0812** [comment]
請參考連結拍攝的操作畫面 https://drive.google.com/file/d/1QwOe4YLhTMw-LkeU9rt-F1FFzCSFWHm4/view?usp=sharing

![image](https://user-images.githubusercontent.com/8065895/53083495-ffa62f80-3539-11e9-8aa5-cf876f9bcc9f.png)

![image](https://user-images.githubusercontent.com/8065895/53083792-81965880-353a-11e9-9ec2-9e328a6667d0.png)

**Comment by sunhapper** [comment]
请问下用的是什么输入法

**Comment by ench0812** [comment]
使用的輸入法採用預設的三星鍵盤，版本: 3.0.23.63
![image](https://user-images.githubusercontent.com/8065895/53139057-5d328e80-35c3-11e9-9e89-e0cd360ba796.png)

**Comment by sunhapper** [comment]
我这没有三星的设备，下载的三星输入法在其他设备上也不能用。。。
先更新下代码，看看https://github.com/sunhapper/SpEditTool/commit/58634af4305e985b13078aba44b120e53f602a1d 这个commit解没解决问题
如果还没有的话看下EmojiSpannableStringBuilder.replace方法，问题应该是出在这里，解决方案应该也是在这里，如果可以自行解决的话欢迎解决之后给我提pr
解决不了的话在replace的地方打下log发给我
```
        if (tb instanceof Spanned) {
            IntegratedSpan[] spans = ((Spanned) tb).getSpans(0, tb.length(), IntegratedSpan.class);
            if (spans != null && spans.length > 0) {
                int spanStart = ((Spanned) tb).getSpanStart(spans[0]);
                int spanEnd = ((Spanned) tb).getSpanEnd(spans[0]);
                Log.i(TAG, "replace: origin:" + this + "  start:" + start + "  end:" + end + "  CharSequence:" + tb
                        + "  spanRange:[" + spanStart + "," + spanEnd + "]");
            }
        }
```

**Comment by ench0812** [comment]
pull 最新版本後的結果
![image](https://user-images.githubusercontent.com/8065895/53165299-4a44ac00-360d-11e9-8c67-c60a39c83d4e.png)

操作畫面:  https://drive.google.com/file/d/1n8DKc-WSFDNbhnR1vJQt-0Rf5CPp8JI6/view?usp=sharing

**Comment by sunhapper** [comment]
我在dev分支修改了一下demo，麻烦切换到dev，pull一下代码看看是什么效果

**Comment by ench0812** [comment]
Cool, 基本上已經滿足操作的狀態，請參考dev版的操作結果
https://drive.google.com/file/d/1IYMwrSKZAdT0Wo1u66bURnm2MAagMVoa/view?usp=sharing
